import { MdOutlineMovieCreation } from "react-icons/md";
import { IoHomeOutline } from "react-icons/io5";
import { IoSaveOutline } from "react-icons/io5";
import { IoSearchOutline } from "react-icons/io5";

export const HEADER_LINKS = [
  {
    id: 1,
    icon: <IoHomeOutline className="text-2xl text-[A1A1A1]" />,
    title: "home",
    url: "/",
  },
  {
    id: 2,
    icon: <MdOutlineMovieCreation className="text-2xl text-[A1A1A1]" />,
    title: "movies",
    url: "/movies",
  },
  {
    id: 3,
    icon: <IoSaveOutline className="text-2xl text-[A1A1A1]" />,
    title: "saved",
    url: "/saved",
  },
  {
    id: 4,
    icon: <IoSearchOutline className="text-2xl text-[A1A1A1]" />,
    title: "search",
    url: "/search",
  },
];

export const MOVIES = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "Fight Club",
  "Forrest Gump",
  "Inception",
  "The Matrix",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Empire Strikes Back",
  "Goodfellas",
  "Schindler's List",
  "Interstellar",
  "Parasite",
  "Gladiator",
  "The Lion King",
  "Avengers: Endgame",
  "Titanic",
  "The Green Mile",
  "Braveheart",
  "Saving Private Ryan",
  "Joker",
  "Django Unchained",
  "The Silence of the Lambs",
  "Se7en",
  "The Prestige",
  "Whiplash",
  "Avatar",
  "Toy Story",
  "Spirited Away",
  "Up",
  "Coco",
  "WALL-E",
  "Inside Out",
  "The Incredibles",
  "Monsters, Inc.",
  "Finding Nemo",
  "Ratatouille",
  "Frozen",
  "Shrek",
  "Harry Potter and the Sorcerer's Stone",
  "The Hunger Games",
  "Twilight",
  "The Fault in Our Stars",
  "Divergent",
  "The Maze Runner",
  "Jumanji",
  "Zootopia",
  "Moana",
  "The Little Mermaid",
  "Beauty and the Beast",
  "Aladdin",
  "Snow White and the Seven Dwarfs",
  "Cinderella",
  "Sleeping Beauty",
  "Tangled",
  "Mulan",
  "Big Hero 6",
  "Despicable Me",
  "Minions",
  "Ice Age",
  "Madagascar",
  "Kung Fu Panda",
  "How to Train Your Dragon",
  "The Lego Movie",
  "Frozen II",
  "Encanto",
  "Turning Red",
  "Luca",
  "Soul",
  "Black Panther",
  "Iron Man",
  "Captain America: The First Avenger",
  "Thor",
  "Spider-Man: No Way Home",
  "Doctor Strange",
  "Guardians of the Galaxy",
  "Ant-Man",
  "Deadpool",
  "X-Men",
  "Logan",
  "Wonder Woman",
  "Aquaman",
  "Justice League",
  "The Batman",
  "Venom",
  "Shang-Chi and the Legend of the Ten Rings",
  "Eternals",
  "Dune",
  "Blade Runner 2049",
  "The Hobbit: An Unexpected Journey",
  "The Chronicles of Narnia",
  "The Jungle Book",
  "Paddington",
  "The Secret Life of Pets",
  "Sing",
  "The Greatest Showman",
  "Les Misérables",
  "La La Land",
  "A Star is Born",
  "The Social Network",
  "The Wolf of Wall Street",
  "Gone Girl",
  "Prisoners",
  "No Country for Old Men",
  "There Will Be Blood",
  "The Departed",
  "The Irishman",
  "The Grand Budapest Hotel",
  "The King's Speech",
  "Argo",
  "Birdman",
  "Spotlight",
  "12 Years a Slave",
  "Slumdog Millionaire",
  "The Curious Case of Benjamin Button",
  "The Pursuit of Happyness",
  "Cast Away",
  "A Beautiful Mind",
  "The Pianist",
  "Life of Pi",
  "Amélie",
  "The Intouchables",
  "The Artist",
  "Her",
  "Room",
  "Little Miss Sunshine",
  "Juno",
  "Silver Linings Playbook",
  "The Big Short",
  "Moneyball",
  "The Blind Side",
  "Million Dollar Baby",
  "Rocky",
  "Creed",
  "Raging Bull",
  "The Fighter",
  "Uncut Gems",
  "Knives Out",
  "Get Out",
  "A Quiet Place",
  "The Babadook",
  "Midsommar",
  "It",
  "The Conjuring",
  "Insidious",
  "Sinister",
  "The Witch",
  "The Ring",
  "Hereditary",
  "Us",
  "The Lighthouse",
  "The Shining",
  "Psycho",
  "Halloween",
  "A Nightmare on Elm Street",
  "Friday the 13th",
  "Scream",
  "The Texas Chainsaw Massacre",
  "The Exorcist",
  "Train to Busan",
  "World War Z",
  "28 Days Later",
  "Shaun of the Dead",
  "Zombieland",
  "I Am Legend",
  "Warm Bodies",
  "The Maze Runner: Scorch Trials",
  "Maze Runner: The Death Cure",
  "The Divergent Series: Insurgent",
  "The Divergent Series: Allegiant",
  "The Twilight Saga: New Moon",
  "The Twilight Saga: Eclipse",
  "The Twilight Saga: Breaking Dawn - Part 1",
  "The Twilight Saga: Breaking Dawn - Part 2",
  "Percy Jackson & the Olympians: The Lightning Thief",
  "Percy Jackson: Sea of Monsters",
  "The Hunger Games: Catching Fire",
  "The Hunger Games: Mockingjay - Part 1",
  "The Hunger Games: Mockingjay - Part 2",
  "Fantastic Beasts and Where to Find Them",
  "Fantastic Beasts: The Crimes of Grindelwald",
  "Fantastic Beasts: The Secrets of Dumbledore",
  "Doctor Strange in the Multiverse of Madness",
  "Thor: Love and Thunder",
  "Black Panther: Wakanda Forever",
];

